### ISSUE TITLE
Project 1 Assessment Link

### ISSUE THREAD

**Issue by romebell** [SEI-ATL/UNIT_1#1]
**Admin**
👀 - [admin] is looking into it
👍 - [admin] Answer issue. Looks good. Code works.

**Students**
🚀 - [student] I get it!
😕 - [student] Still confused
😄 - [student] A simple error
🎉 - [student] My code now works

**Admin/Students**
❤️ - [student/admin] Love the topic or code snippet
👎 - [student/admin] Code didn't work

**Comment by romebell** [comment]
- [ ] Post Github Pages link
- [ ] Post their repo link

**Comment by sschneeberg** [comment]
Pages -->  https://sschneeberg.github.io/project-1-assessment/

Repo --> https://github.com/sschneeberg/project-1-assessment

**Comment by ruvvet** [comment]
https://ruvvet.github.io/P1-assessment/
https://github.com/ruvvet/P1-assessment/

**Comment by nitishdayal** [comment]
- https://nitishdayal.github.io/GA_Assessment_1/
- https://github.com/nitishdayal/GA_Assessment_1/

**Comment by JJURIZ** [comment]
[GitHub Pages Link](http://jeremyuriz.com/GA-project-1-assessment/)
[Repo Link](https://github.com/JJURIZ/GA-project-1-assessment)

**Comment by NikkiHmltn** [comment]
[Pages Link](https://nikkihmltn.github.io/project-1-assessment/)
[Repo Link](https://github.com/NikkiHmltn/project-1-assessment)

**Comment by codebypaul** [comment]
site: https://codebypaul.github.io/project-1-assessment/
repo: https://github.com/codebypaul/project-1-assessment/

**Comment by andrewemcmanus** [comment]
repo: https://github.com/andrewemcmanus/project-1-assessment/
deployment: https://andrewemcmanus.github.io/project-1-assessment/

**Comment by NikkiHmltn** [comment]
[Site](https://nikkihmltn.github.io/project-1-assessment/)
[Repo](https://github.com/NikkiHmltn/project-1-assessment)

**Comment by tuhoalyhuynh** [comment]
https://tuhoalyhuynh.github.io/project-1-assessment/

https://github.com/tuhoalyhuynh/project-1-assessment

**Comment by tcgilbert** [comment]
https://github.com/tcgilbert/project-1-assessment

https://tcgilbert.github.io/project-1-assessment/

**Comment by zfinnan** [comment]
https://zfinnan.github.io/project-1-assessment/

https://github.com/zfinnan/project-1-assessment

**Comment by alanavery** [comment]
Repo: https://github.com/delayedaa/project-1-assessment

Deployment: https://delayedaa.github.io/project-1-assessment/

**Comment by anonyymous1** [comment]
https://github.com/anonyymous1/project-1-assessment

https://anonyymous1.github.io/project-1-assessment/

**Comment by tuanhrex** [comment]
https://tuanhrex.github.io/project-1-assessment/

https://github.com/tuanhrex/project-1-assessment

**Comment by richardleung1** [comment]
Deployment: https://richardleung1.github.io/project-1-assessment/
Repository: https://github.com/richardleung1/project-1-assessment

**Comment by CoreyWilson319** [comment]
Repository: https://github.com/CoreyWilson319/project-1-assessment
Deployment: https://coreywilson319.github.io/

**Comment by AJStrizzy** [comment]
Deployment: https://ajstrizzy.github.io/Project-1-Assessment/
Repository: https://github.com/AJStrizzy/Project-1-Assessment

**Comment by lev-choubine** [comment]
Deployment: https://lev-choubine.github.io/project-1-assessment/
Repository: https://github.com/lev-choubine/project-1-assessment

**Comment by AJStrizzy** [comment]
Deployment: https://ajstrizzy.github.io/Project-1-Assessment/
Repository: https://github.com/AJStrizzy/Project-1-Assessment

**Comment by wjlock** [comment]
Deployment: https://wjlock.github.io/project-1-assessment/
Repository: https://github.com/wjlock/project-1-assessment

**Comment by ABarranco95** [comment]
Deployment: https://abarranco95.github.io/project-1-assessment/
Repo: https://github.com/ABarranco95/project-1-assessment

**Comment by fmuwanguzi** [comment]
Deployment: https://fmuwanguzi.github.io/project-one-assesment/
Repository: https://github.com/fmuwanguzi/project-one-assesment

**Comment by tylerdance** [comment]
Repo: https://github.com/tylerdance/project-1-assessment
Deployment: https://tylerdance.github.io/project-1-assessment/

**Comment by AlexJBustillos** [comment]
repo: https://github.com/AlexJBustillos/Project-1-assessment
deployment: confused on how to deploy

**Comment by Swolepenguin** [comment]
repo: https://github.com/Swolepenguin/project-1-assessment

**Comment by JaxonNarramore** [comment]
repo: https://github.com/JaxonNarramore/project-1-assessment

**Comment by edgerees** [comment]
repo, having some issues on deploying. 
https://github.com/edgerees/project-1-assessment.git

**Comment by jtreeves** [comment]
Page: https://jtreeves.github.io/project-1-assessment/
Repo: https://github.com/jtreeves/project-1-assessment

**Comment by NykywanP** [comment]
Page: https://github.com/NykywanP/Project-1-assessment

**Comment by canourrea23** [comment]
https://github.com/canourrea23/project-1-assessment
https://canourrea23.github.io/project-1-assessment/
