### ISSUE TITLE
OOP-formula1-nyt-more

### ISSUE THREAD

**Issue by romebell** [SEI-ATL/UNIT_1#6]
https://github.com/SEI-ATL/formula1-nyt-more

**Comment by NykywanP** [comment]
https://github.com/SEI-ATL/formula1-nyt-more..  Task complete.

**Comment by codebypaul** [comment]
completed: https://github.com/codebypaul/formula1-nyt-more.git

**Comment by maddevred** [comment]
https://github.com/marjames98/formula1-nyt-more
